version: "3.8"

volumes:
  cache-volume: {}
  db-volume: {}
  etc-volume: {}
  index-volume: {}
  git-volume: {}

services:
  gerrit:
    image: gerritcodereview/gerrit
    environment:
      CANONICAL_WEB_URL: http://localhost:6060
    volumes:
      - db-volume:/var/gerrit/db
      - etc-volume:/var/gerrit/etc
      - cache-volume:/var/gerrit/cache
      - index-volume:/var/gerrit/index
      - git-volume:/var/gerrit/git
    ports:
      - "29418:29418"
      - "6060:8080"
