name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    name: ""
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.3
        with:
          maven-version: 3.8.2

      - name: Build
        run: |
          export VERSION="${GITHUB_REF##*/v}"
          mvn -Drevision=${VERSION} clean package
          sha256sum target/codeowners-${VERSION}.jar > target/codeowners-checksums.txt

      - name: Upload
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/codeowners-*.jar
            target/codeowners-checksums.txt
